#!/bin/bash

if ! [[ -d ".venv" ]]; then
    echo "The usage of a virtual environment is recommended."
    echo "This script searches for an enviroment in: '.venv'"
else
    source ./.venv/bin/activate
fi
python ./.aoc/aoc.py "$@"